apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      imagePullSecrets:
          - name: gcr-json-key
      containers:
        - image: asia-east1-docker.pkg.dev/sleepr-467504/notifications/production:final
          name: notifications
          imagePullPolicy: Always
